version: "3.8"
name: product-service
services:
  product-db:
    image: mysql:latest
    container_name: product-service_db
    environment:
    - MYSQL_ROOT_PASSWORD=srinivasH53@  # Root password
    - MYSQL_DATABASE=products_db        # Database to initialize                 # Optional (root user is default)
    - MYSQL_PASSWORD=srinivasH53@
    ports:
      - "3307:3306"

    healthcheck:
      test: ["CMD-SHELL","mysql-ready -U mysql"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"


  kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
